plugins {
    id 'base'
}

group = project.maven_group
version = project.mod_version

subprojects {
    group = rootProject.group
    version = rootProject.version

    tasks.withType(AbstractArchiveTask).configureEach {
        archiveVersion = ''
    }
}

def collectedJarDir = layout.buildDirectory.dir('collected-jars')

tasks.register('collectBuiltJars', Copy) {
    dependsOn(':fabric:build', ':quilt:build', ':forge:build', ':neoforge:build')

    into(collectedJarDir)

    from(project(':fabric').layout.buildDirectory.dir('libs')) {
        include "RailOptimization-${project.mod_version}-fabric.jar"
    }
    from(project(':quilt').layout.buildDirectory.dir('libs')) {
        include "RailOptimization-${project.mod_version}-quilt.jar"
    }
    from(project(':forge').layout.buildDirectory.dir('libs')) {
        include "RailOptimization-${project.mod_version}-forge.jar"
    }
    from(project(':neoforge').layout.buildDirectory.dir('libs')) {
        include "RailOptimization-${project.mod_version}-neoforge.jar"
    }
}

tasks.named('build') {
    dependsOn(
            ':fabric:build',
            ':quilt:build',
            ':forge:build',
            ':neoforge:build',
            'collectBuiltJars'
    )
}
