org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn

mod_version=1.2
maven_group=me.noramibu
archives_base_name=RailOptimization

mod_id=railoptimization
mod_name=RailOptimization
mod_license=LGPL-3.0
mod_authors=noramibu, FX - PROCESS, EasterGhost
mod_description=A simple mod that makes powered/activator rails turn on/off up to 4x faster

minecraft_version=26.1
java_version=25

loom_version=1.16-SNAPSHOT
fabric_loader_version=0.18.6
fabric_api_version=0.145.1+26.1

quilt_loader_version=0.30.0-beta.7

forge_gradle_version=[7.0.17,8)
forge_version=62.0.9
forge_loader_version_range=[62,)
forge_minecraft_version_range=[26.1,26.1.1)
eventbus_validator_version=7.0.1

moddevgradle_version=2.0.141
neo_version=26.1.0.19-beta
neo_version_range=[26.1.0.19-beta,)
neo_minecraft_version_range=[26.1,26.1.1)

mixin_version=0.8.5
